FROM airhacks/payara-micro
ENV ARCHIVE_NAME Consolidator.war
COPY target/${ARCHIVE_NAME} ${INSTALL_DIR}

ENV MONGO_IP_ADDRESS mongoer
ENV MONGO_PORT 27017
ENV MONGO_DATABASE_NAME ContainerDB
ENV MONGO_COLLECTION_NAME Tags

EXPOSE 8080